### ISSUE TITLE
QUESTION: Is there no Python v3 lib for all the v3 routes?

### ISSUE THREAD

**Issue by rocktimsaikia** [Flutterwave/Python-v2#123]
`https://api.flutterwave.com/v3/`

**Comment by corneliusyaovi** [comment]
Hello @rocktimsaikia,

We are working on a library that uses the v3 endpoints. We'll provide updates on our development as we reach certain milestones.

**Comment by rocktimsaikia** [comment]
Thanks for the update. In the meantime, we will be using the v3 API endpoints directly.
